#!/usr/bin/env node

// Deletes the service associated with the public path passed.

var util = require('./util'),
    program = require('commander'),
    config = require('./config'),
    logger = require('./log');

var db = require(config.database.type);

program
    .description('Deletes the service associated with the public path.')
    .parse(process.argv);

if (program.args.length !== 1) {
    logger.error('Invalid number of arguments. Usage: ./cli deleteService <publicPath>');
    console.log(program.help());

} else {

    var publicPath = program.args[0];

    if (!util.pathRegExp.test(publicPath)) {
        logger.error(util.invalidPathError);

    } else {

        db.deleteService(publicPath, function(err) {

            if (err) {
                logger.error(err);

            } else {
                logger.info('Service ' + publicPath + ' deleted.')
            }
        });
    }
}