#!/usr/bin/env node

// Binds the specified administrator to the service specified by its public path.

var program = require('commander'),
    config = require('./config'),
    logger = require('./log'),
    util = require('./util');

var db = require(config.database.type);

program
    .description('Adds the specified administrator to the service specified by the public path.')
    .parse(process.argv);

if (program.args.length !== 2) {
    logger.error('Invalid number of arguments. Usage: ./cli bindAdmin <userId> <publicPath>');

} else {

    var userId = program.args[0];
    var publicPath = program.args[1];

    if (!util.pathRegExp.test(publicPath)) {
        logger.error(util.invalidPathError);

    } else {

        db.bindAdmin(userId, publicPath, function(err) {
            if (err) {
                logger.error(err);
            } else {
                logger.info('Admin ' + userId + ' added to service ' + publicPath);
            }
        });
    }
}