#!/usr/bin/env node

var cli = require('commander');
var db = require('./db_Redis.js');

cli
    .description('Configuration tool for accounting proxy.')
    .version('0.0.1');

// Add new service command
cli
    .command('addService [path] [port]')
    .description('Add new service to proxy database.')
    .action(function(path, port) {
        if (/\/((\w+)\/?)*$/.test(path) &&
            /\/((\w+)\/?)*$/.test(path) &&
            /^\d*$/.test(port))
            db.newService(path, port, function(err) {
                if (err)
                    console.log(err);
            });
        else {
            console.log("[ERROR] Invalid parameters.");
        }
    });

// Map service command
cli
    .command('mapService [publicPath] [privatePath] [port]')
    .description('Map public path with private path and port')
    .action(function(publicPath, privatePath, port) {
        if  (/\/((\w+)\/?)*$/.test(privatePath) && 
            /^\d*$/.test(port))
            db.mapService(publicPath, privatePath, port, function(err){
                if(err)
                    console.log(err);
            });
        else {
            console.log("[ERROR] Invalid parameters.");
        }
    });


// Get service information
cli
    .command('getService [publicPath]')
    .description('Get service information')
    .action(function(publicPath) {
        if (/\/((\w+)\/?)*$/.test(publicPath))
            db.getService(publicPath, function(err, data) {
                if(err)
                    console.log(err);
                else if (data === undefined)
                    console.log('No data avaliable');
                else
                     console.log("Private path: " + data['privatePath'] + "  Port: " + data['port']);
                });
        else 
            console.log("[ERROR] Invalid parameters.");
    });


// Delete service command
cli
    .command('deleteService [path] [port]')
    .description('Delete a service from proxy database.')
    .action(function(path, port) {
        if (/\/((\w+)\/?)*$/.test(path) &&
            /^\d*$/.test(port))
            db.deleteService(path, port, function(err) {
                if (err)
                    console.log(err);
            });
        else {
            console.log("[ERROR] Invalid parameters.");
        }
    });

cli
    .command('getInfo [user]')
    .description('Get user\'s information.')
    .action(function(user) {
        db.getInfo(user, function(err, data) {
            if (err)
                console.log('Error occur in DB.');
            else if (data === undefined)
                console.log('No data avaliable.');
            else {
                console.log("[FORMAT: Organization - Name - Version - API_KEY]");
                for (i in data) {
                    console.log(data[i].organization + " - " +
                                data[i].name + " - " +
                                data[i].version + " - " +
                                data[i].API_KEY);
                }
            }
        });
    });

cli.parse(process.argv);
